apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-demo
  labels:
    app: redis-demo
spec:
  selector:
    matchLabels:
      app: redis-demo
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: redis-demo
      labels:
        app: redis-demo
    spec:
      containers:
      - name: redis-demo
        image: vitali84/redis-demo
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
          limits:
            cpu: "0.5"
            memory: "256Mi"
        ports:
        - containerPort: 3000
          name: redis-demo
        env:
        - name: REDIS_HOST
          value: 'redis:6379'
#      - name: webapp
#        image: training/webapp
#        resources:
#          requests:
#            cpu: "0.2"
#            memory: "128Mi"
#          limits:
#            cpu: "0.5"
#            memory: "256Mi"