apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-demo
  name: redis-demo
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: redis-demo
  sessionAffinity: None
  type: NodePort
